TRUNCATE TABLE teams RESTART IDENTITY CASCADE;
TRUNCATE TABLE projects RESTART IDENTITY CASCADE;
TRUNCATE TABLE annotations RESTART IDENTITY;
TRUNCATE TABLE environments RESTART IDENTITY;
TRUNCATE TABLE executions RESTART IDENTITY;
